"frontend/**" !"frontend/dist/**"{
    indir: "./frontend"
    prep: npm run build:dev
}
"frontend/dist/**"{
    prep: rm .dirty
    prep: touch .dirty
}
"backend/**/*.go" {
    daemon: go run ./backend
    prep: rm .dirty
    prep: touch .dirty
}
{
    daemon: go tool devd -ow .dirty http://localhost:3000
}
